defmodule AshJoinBug.MysqlRepo.Migrations.CreateResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_mysql.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:resource2mysql, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :resource1_id, :uuid
      add :value, :text
    end

    create table(:resource1mysql, primary_key: false) do
      add :id, :uuid, null: false, primary_key: true
      add :resource2_id, :uuid
      add :value, :text
    end

    # alter table(:resource2mysql) do
    #   modify :resource1_id,
    #          references(:resource1mysql,
    #            column: :id,
    #            name: "resource2mysql_resource1_id_fkey",
    #            type: :uuid
    #          )
    # end

    # alter table(:resource1mysql) do
    #   modify :resource2_id,
    #       references(:resource2mysql,
    #         column: :id,
    #         name: "resource1mysql_resource2_id_fkey",
    #         type: :uuid
    #       )
    # end
  end

  def down do
    # drop constraint(:resource1mysql, "resource1mysql_resource2_id_fkey")
    # drop constraint(:resource2mysql, "resource2mysql_resource1_id_fkey")
    drop table(:resource1mysql)
    drop table(:resource2mysql)
  end
end
