defmodule AshJoinBug.PostgresRepo.Migrations.CreateResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:resource2pg, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource1_id, :uuid
      add :value, :text
    end

    create table(:resource1pg, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :resource2_id, :uuid
      add :value, :text
    end

    # alter table(:resource2pg) do
    #   modify :resource1_id,
    #          references(:resource1pg,
    #            column: :id,
    #            name: "resource2pg_resource1_id_fkey",
    #            type: :uuid,
    #            prefix: "public"
    #          )
    # end

    # alter table(:resource1pg) do
    #   modify :resource2_id,
    #       references(:resource2pg,
    #         column: :id,
    #         name: "resource1pg_resource2_id_fkey",
    #         type: :uuid,
    #         prefix: "public"
    #       )
    # end
  end

  def down do
    # drop constraint(:resource1pg, "resource1pg_resource2_id_fkey")

    # alter table(:resource1pg) do
    #   remove :value
    #   remove :resource2_id
    # end

    # drop constraint(:resource2pg, "resource2pg_resource1_id_fkey")

    # alter table(:resource2pg) do
    #   modify :resource1_id, :uuid
    # end

    drop table(:resource1pg)

    drop table(:resource2pg)
  end
end
